language: objective-c
os: osx
osx_image: xcode10.2
env:
  - TOOLCHAINS=swift
cache:
  - bundler
before_install:
  - bundle install
  - brew update && brew bundle
script:
  - swift test
  - make install
  - bash -c "cd Sample && fastlane test"
